services:
  mysql:
    image: mysql:8.0
    container_name: project-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 10s
      retries: 5
      start_period: 30s  # Optional, increase time before starting health checks
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_ABSOLUTE_URI: http://localhost:8081/
    ports:
      - "8081:80"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: project-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_DATABASE: project_db
      DB_USERNAME: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: project-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network: